#!/bin/bash

# Create a new figlet (ascii art) from the input.

figl() {
  font=${FIGL_FONT:-puffy}
  declare -a buf
  while IFS= read -r line; do
    buf+=("$line")
  done
  for line in "${buf[@]}"; do
    figlet -f "$font" -c "${line}" | head -6
  done
}

figl "$*"
