#!/bin/sh

config="${HOME}/.config"

_make_dirs() {
  test ! -d "${config}" && mkdir "${config}"
}

_remove_git() {
  test -d "${config}/git" && rm "${config}/git"
}

_link_git() {
  ln -sfv "${PWD}/git" "${config}"
}

#------------------------------- main -------------------------------
_make_dirs && _link_git
