#!/bin/sh

set -e

dir="${PWD}"

cd "${dir}/zsh" && ./setup
#cd "${dir}/scripts" && ./setup
ln -sfv "${dir}/scripts/scripts" ~/.local/scripts
cd "${dir}/vim" && ./setup
cd "${dir}/git" && ./setup
cd "${dir}/tmux" && ./setup
