#!/usr/bin/env bash

XDG_DATA_HOME=${XDG_DATA_HOME:-"$HOME"/.local/share}

install() {
	[[ ! -d "$XDG_DATA_HOME/gopass/stores/root" ]] &&
		gopass clone ssh://git@git.housh.dev:2222/michael/passwordstore.git
}

uninstall() {
	[[ -d "$XDG_DATA_HOME/gopass" ]] && rm -rf "$XDG_DATA_HOME/gopass"
}

arg=${1:-""}
[[ $arg == "install" ]] && install
[[ $arg == "uninstall" ]] && uninstall
