#!/usr/bin/env bash

set -e
set -o nounset
set -o pipefail

SCRIPTS="${DEV_ENV}/env/.local/scripts"

install() {
	log "	Setting user shell to 'zsh'."
	sudo chsh --shell "$(which zsh)"
	log "	Enabling up systemd services."
	sudo systemctl daemon-reload
	sudo systemctl enable --now pcscd.service
	sudo systemctl enable --now firewalld.service
	systemctl --user enable --now logout-task.service
	systemctl --user enable --now battery-monitor.timer
	systemctl --user enable --now tmux-kill-sessions.timer
	SCRIPTS="$SCRIPTS" "$SCRIPTS/kanatactl" service install --prompt
}

arg=${1:-""}
[[ $arg == "install" ]] && install
