theme = "nightfox"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
shell = ["zsh", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false