#!/bin/sh

set -e

# Creates a new `zet` inside the House Call Pro `Zettlekasten` directory.

_create() {
  # Complete
  echo "Create..."
}

_commit() {

  echo "Commit..."
}

dirname="$(isosec)"
mkdir "${HCP_NOTES}/${dirname}"
dir="$HCP_NOTES/$dirname"
readme="$dir/README.md"
title="$*"
printf "# %s\n\n" "${title}" > "${readme}"
message="${title:-"Autocommit message"}"
cd "$dir"
git pull -q
git add -A "$dir"
git commit -m "$message"
git push
cd -
vi "${readme}"
