#!/bin/sh

# Creates a new executable file in the $SCRIPTS directory.

# check if the scripts path / environment variable is set
test ! -n "${SCRIPTS}" && echo "SCRIPTS not set" && exit 1;

# fallback to check if the name arg ${1} exists, if not show usage text.
test ! -n "${1}" && \
  echo "usage: newscript <name> <optional: shell>" && \
  echo "shell defaults to sh if not supplied" && \
  exit 1;

path="${SCRIPTS}/${1}"
shell="${2:-sh}"

if [ -e "${path}" ]; then
  echo "Already exists try:"
  echo "vi ${path}"
  exit 1
fi

printf "#!/bin/%s\n\n" "${shell}" > "${path}"
chmod +x "${path}"
exec "${EDITOR}" +2 "${path}"

