#!/usr/bin/env zsh

# Adapted from: https://github.com/ThePrimeagen/.dotfiles/blob/master/bin/.local/scripts/tmux-sessionizer

declare -a findPaths=("$HOME")

function fpath_prepend() {
  declare arg
  for arg in "$@"; do
    test -d $arg || continue
    findPaths=("$arg" "$findPaths")
  done
}

if [[ $# -eq 1 ]]; then
  selected=$1
else

  fpath_prepend "$REPOS" \
    "$LOCAL_REPOS" \
    "$GHREPOS" \
    "$GHREPOS"

  # Some of my machines, projects is a symlink to $REPOS, so ignore it.
  # On other machines, it is local versions of projects, so add it.
  if [[ ! -L "$HOME/projects" ]]; then
    findPaths+="$HOME/projects"
  fi

  if [[ -d "$REPOS/github.com" ]]; then
    for dir in $(find "$REPOS/github.com" -mindepth 1 -maxdepth 1 -type d); do
      # prepends to the array.
      findPaths=($dir $findPaths)
    done
  fi

  if [[ -d "$REPOS/local" ]]; then
    # prepends to the array.
    findPaths=("$REPOS/local" $findPaths)
  fi

  selected=$(find -L "${(@)findPaths}" -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t $selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected_name
fi

tmux switch-client -t $selected_name
