#!/bin/sh

if [ $# -eq 1 ]; then
  session=${1}
else
  session=$(tmux list-sessions -F \#S | gum filter --placeholder "Pick a session...")
fi

if [ -z "$session" ]; then
  exit 0
fi

tmux switch-client -t "$session" || tmux attach -t "$session"
