#!/bin/sh

session=${1}

if [ -z "$session" ]; then
  choice=$(tmux list-sessions -F \#S | gum filter --placeholder "Pick a session...")
  tmux switch-client -t "$choice" || tmux attach -t "$choice"
else
  tmux switch-client -t "$session" || tmux attach -t "$session"
fi
