#!/bin/sh

set -e

if test -z "$(type vim)"; then
  echo "Does not look like you have vim installed."
  exit 1
fi

mkdir "${HOME}/.vim" >/dev/null 2>&1
ln -sfv "${PWD}/.vim/vimrc" "${HOME}/.vim/vimrc"




