#!/usr/bin/env bash

# Get the weather for the given location.

location=${1:-Cincinnati}
shouldContinue="1"

while [[ $shouldContinue == "1" ]]; do
  echo -e "\e[H\e[2J" # clears the screen.
  curl "wttr.in/$1"
  shouldContinue=$(gum confirm "Quit / Refresh" --affirmative Quit --negative Refresh && echo "0" || echo "1")
done

echo -e "\e[H\e[2J" # clears the screen.
