#!/bin/zsh

# Change / select an nvim configuration.
#
# The configuration's need to be in the ~/.config folder
# to work properly.
#
main() {
  items=("default" "m-housh" "kickstart" "lazy")
  config=$(printf "%s\n" "${items[@]}" \
    | fzf --prompt=" Neovim Config ➣ " --height=50% --layout=reverse --border --exit-0
  )
  if [ -z "$config" ]; then
    echo "Nothing selected"
    return 0
  elif [ $config == "default" ]; then
    config=""
  fi
  unset VIMINIT && unset MYVIMRC && export NVIM_APPNAME=$config && nvim $@
}

main "$@"
