#!/bin/zsh
#
# Toggles the state of the internal laptop monitor, which is useful
# when I'm connected to an external monitor / docks.

monitor="eDP-1"

if hyprctl monitors | grep -q "$monitor"; then
  hyprctl keyword monitor "$monitor,disable" 1>/dev/null
else
  hyprctl keyword monitor "$monitor,enable" 1>/dev/null
fi
