"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
[](color_orange)\
$os\
$username\
$hostname\
[](bg:color_pink fg:color_orange)\
$directory\
[](fg:color_pink bg:color_bg1)\
$git_branch\
$git_status\
$line_break$custom\
$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
color_fg0 = '#cad3f5'
color_bg1 = '#1e2030'
color_bg3 = '#24273a'
color_blue = '#8aadf4'
color_aqua = '#94e2d5'
color_green = '#a6e3a1'
color_orange = '#f5a97f'
color_purple = '#c6a0f6'
color_lavender = '#b4befe'
color_red = '#ed8796'
color_yellow = '#eed49f'
color_grey = '#585b70'
color_maroon = '#eba0ac'
color_pink = '#f5c2e7'
color_text = '#585b70'

[os]
disabled = false
style = "bold bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bold bg:color_orange fg:color_text"
style_root = "bold bg:color_orange fg:color_text"
format = '[ $user ]($style)'

[hostname]
ssh_only = true
format = '[$ssh_symbol : $hostname](bold bg:color_orange fg:color_text)'
disabled = false

[directory]
style = "bold fg:color_text bg:color_pink"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo = true

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_bg1"
format = '[[ $symbol $branch ](bold fg:color_green bg:color_bg1)]($style)'

[git_status]
style = "bold bg:color_bg1"
format = '[[($all_status$ahead_behind )](bold fg:color_green bg:color_bg1)]($style)'

[line_break]
disabled = false

[custom.git_identity_lock]
command = 'printf "🔒"'
when = 'test "${GIT_HUMAN_IDENTITY:-}" = "1" || test "${GIT_IDENTITY_HUMAN_SHELL:-}" = "1"'
format = '[$output](bold fg:color_yellow) '

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
