#!/bin/sh

HISTSIZE=200
HISTFILE=$ZDOTDIR/history

# shell
export SHELL="$(which zsh)"

# Allow useful scripts in ~/.bin to be in the search path.
export PATH=~/.bin:$PATH

# Allow git to work on mounted volumes
export GIT_DISCOVERY_ACROSS_FILESYSTEM=1

# Add homebrew to the path
if [ -d /opt/homebrew ]; then
  export PATH=/opt/homebrew/bin:$PATH
  export PATH=/opt/homebrew/sbin:$PATH
fi

# zsh-completions installed by homebrew
if type brew &>/dev/null; then
 FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

 autoload -Uz compinit
 compinit
fi

export EDITOR="nvim"

