#!/usr/bin/env bash

if ! command -v yay >/dev/null 2>&1; then
  sudo pacman -S --noconfirm --needed git base-devel
  git clone https://aur.archlinux.org/yay.git ~/yay
  cd ~/yay
  makepkg -si
  rm -rf ~/yay
fi

# Basics
yay -S --noconfirm --needed \
  asahi-desktop-meta \
  bat \
  bc \
  catppuccin-gtk-theme-mocha \
  sddm-theme-catppuccin \
  eza \
  fastfetch \
  fzf \
  git-lfs \
  gum \
  hyprpaper \
  hyrpidle \
  hyprlock \
  jq \
  neovim \
  nodejs \
  npm \
  nwg-look \
  pam-u2f \
  pcsc-tools \
  starship \
  swaync \
  tldr \
  tmux \
  tree-sitter-cli \
  wl-clipboard \
  yubikey-manger \
  zoxide \
  zsh

# Fonts
yay -S --noconfirm \
  ttf-jetbrains-mono-nerd \
  ttf-firacode \
  ttf-inconsolata-nerd
