#!/usr/bin/env bash

if ! command -v yay >/dev/null 2>&1; then
  sudo pacman -S --noconfirm --needed git base-devel
  git clone https://aur.archlinux.org/yay.git ~/yay
  cd ~/yay
  makepkg -si
  rm -rf ~/yay
fi

# Packages
yay -S --noconfirm --needed \
  bat \
  eza \
  fastfetch \
  fzf \
  git-lfs \
  gum \
  jq \
  neovim \
  nodejs \
  npm \
  starship \
  tldr \
  tmux \
  tree-sitter-cli \
  zoxide \
  zsh

# Fonts
yay -S --noconfirm \
  ttf-jetbrains-mono-nerd \
  ttf-firacode \
  ttf-inconsolata-nerd
