#!/usr/bin/env bash

SCRIPTS=${SCRIPTS:-$HOME/.local/scripts}
THIS_FILE=${BASH_SOURCE[0]}
THIS=$(basename $THIS_FILE)

usage() {
  cat <<EOF

Utility for getting fzf preview data.

USAGE:

  $ $THIS [MODE] [ARG...]

MODES:

  monitor <id> <keys>:            Get monitor data, optionally providing keys to return.
  window <address> <keys>:        Get window data, optionally providing keys to return.
  workspace <id> <keys>:          Get workspace data, optionally providing keys to return.
  utlis <name> <config>:          Get utils-launcher data.

EXAMPLE:

Here's an example of getting window data, but only returning "title", "workspace", and "address".

  $ $THIS window "0xaaaaea92a7e0" "{title, workspace, address}"

EOF
}

# Logging utility function, use in place of echo.
log() {
  logging log --source "$THIS_FILE" "$@"
}

################################################################################
# MAIN
################################################################################

# Setup logging file and label.
source "$SCRIPTS/hypr/logging"
setup-logging "$THIS"

if [[ ! ${#@} -ge 2 ]]; then
  log --error "Unexpected argument count: ${#@}, expected at least: 2"
  usage && exit 1
fi

mode="$1"
# Remove single quotes from the arg.
arg="${2//\'/}"

if [[ $mode == "monitor" ]]; then
  keys="$3"
  if [[ -n $keys ]]; then
    hyprctl monitors -j | jq -C ".[] | select(.id == $arg) | $keys"
  else
    hyprctl monitors -j | jq -C ".[] | select(.id == $arg)"
  fi
elif [[ $mode == "window" ]]; then
  keys="$3"
  if [[ -n $keys ]]; then
    hyprctl clients -j | jq -C ".[] | select(.address == \"$arg\") | $keys"
  else
    hyprctl clients -j | jq -C ".[] | select(.address == \"$arg\")"
  fi

elif [[ $mode == "workspace" ]]; then
  keys="$3"
  if [[ -n $keys ]]; then
    hyprctl workspaces -j | jq -C ".[] | select(.id == $arg) | $keys"
  else
    hyprctl workspaces -j | jq -C ".[] | select(.id == $arg)"
  fi
elif [[ $mode == "utils" ]]; then
  config="${3//\'/}"
  if [[ ! -f $config ]]; then
    log --error "No utility-launcher config found: $config"
    exit 1
  fi
  desc=$(jq -C ".[] | select(.name == \"$arg\") | .description" $config)
  exec=$(jq -C ".[] | select(.name == \"$arg\") | .exec" $config)
  echo -e "\n${desc[@]}\n\n"
  echo -e "\e[31mEXEC:\e[0m $exec\n"
else
  log --error "Unexpected mode: $mode"
  usage && exit 1
fi
