#!/bin/sh

WAYBAR_PID=$(pgrep -x waybar)

if [ -n "$WAYBAR_PID" ]; then
  # kill waybar process if it's running.
  kill "$WAYBAR_PID"
else
  # start waybar in the background.
  setsid uwsm app -- waybar >/dev/null 2>&1 &
fi
