#!/usr/bin/env bash

set -e
set -o nounset
set -o pipefail

THIS_FILE=${BASH_SOURCE[0]}
THIS=$(basename $THIS_FILE)
SCRIPTS=${SCRIPTS:-$HOME/.local/scripts}

usage() {
  cat <<EOF

Show a table with details about the currently active windows. You can choose a window and perform
an action. 

USAGE:

  $ $THIS <command> <flags>

FLAGS:

  -h | --help:                      Show this page.

COMMANDS:

  close:          Close window(s).
  launch:         Launch in a new terminal window, user will be prompted what to do with selected window.

Run "$THIS <command> --help" for more information on a command.

EOF
}

window_class="com.ghostty.$THIS"
window_padding_x="10"
should_quit="0"

log() {
  logging log --source "$THIS_FILE" "$@"
}

launch_usage() {
  cat <<EOF

Launches in a new terminal window.

USAGE:
  
  $ $THIS launch

EOF
}

# Launch in a new terminal window.
launch() {
  if [[ $@ =~ ^-h ]] || [[ $@ =~ ^--help ]]; then
    launch_usage && exit 0
  fi

  ghostty --class="$window_class" --window-padding-x="$window_padding_x" \
    --keybind="ctrl+c=quit" \
    -e "${BASH_SOURCE[0]}" "${launch_args[@]}"
}

handle_selected_value() {
  local selection=""
  read -r selection

  if [[ -z $selection ]]; then
    log "No selected value."
    return 1
  fi

  log "Prompting for action, window: '$selection'"

  local res=$(echo "$selection" | "$SCRIPTS/hypr/utils/windows/window-action-picker")
  log "Action callback result: $res"
  echo "$res"

}

prompt_for_window_selection() {
  local selected_value=$("$SCRIPTS/hypr/window-picker")
  local status=$?
  if [[ $status -ne 0 ]]; then
    exit $status
  fi
  echo "$selected_value"
}

##################################################
# MAIN
##################################################

# Setup logging file and label.
source "$SCRIPTS/hypr/logging"
setup-logging "$THIS"

while [[ $# -gt 0 ]]; do
  if [[ $1 == "close" ]]; then
    shift
    THIS="$THIS close" "$SCRIPTS/hypr/utils/windows/close-windows" "$@"
    exit $?
  elif [[ $1 == "launch" ]]; then
    shift
    launch "$@" && exit 0
  elif [[ $1 == "-h" ]] || [[ $1 == "--help" ]]; then
    usage && exit 0
  else
    log --error "Unhandled arg: $1"
    exit 1
  fi
  shift
done

# Load colors if they haven't been loaded already.
[[ -z ${FZF_DEFAULT_OPTS} ]] &&
  [[ -f $SCRIPTS/catppuccin-colors ]] &&
  source $SCRIPTS/catppuccin-colors

trap 'log "Stoping..."; should_quit="1"' SIGINT

while [[ $should_quit -eq 0 ]]; do
  res=$(prompt_for_window_selection | handle_selected_value)
  if [[ ! $res =~ ^back ]]; then
    should_quit=1
  elif [[ $res == "back:close" ]]; then
    sleep 0.3 # allow time for windows close, to prevent showing closed windows.
  fi
  log "Should quit: $should_quit"
done
