tap "homebrew/cask"
tap "homebrew/cask-fonts"

# TODO: Make the application directory a global variable ??
# set arguments for all 'brew install --cask' commands
cask_args appdir: "~/Applications", require_sha: true

# formula
brew "fd"               # required for some neovim plugins
brew "git"
brew "mas"
brew "neovim"
brew "node"             # required for some LSP servers in neovim
brew "ripgrep"
brew "stow"
brew "swift-format"
brew "zsh"

# casks
cask "docker"
cask "google-chrome"
cask "iterm2"
cask "paw"
#cask "sketchup-pro"

# fonts
cask "font-inconsolata-nerd-font"
