tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "federico-terzi/espanso"
tap "m-housh/formula"

# TODO: Make the application directory a global variable ??
# set arguments for all 'brew install --cask' commands
#cask_args appdir: "~/Applications", require_sha: true

# formula
brew "espanso"              # Espanso: Text expander
brew "fd"                   # required for some neovim plugins
brew "figlet"               # for ascii art / text
brew "gh"                   # Github CLI
brew "git"
brew "httpie"               # better curl / api's from command line.
brew "jq"                   # json utilities
brew "mas"                  # Mac AppStore apps from cli
#brew "neovim"
brew "pure"                 # for cli prompt
brew "ripgrep"
brew "swift-format"         # for formatting swift files
brew "swift-zet"            # for managing zettelkasten notes
brew "tmux"                 # terminal multi-plexer
brew "vim"
brew "zsh"
brew "zsh-completions"

# fonts
cask "font-inconsolata-nerd-font"
