tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "federico-terzi/espanso"

# TODO: Make the application directory a global variable ??
# set arguments for all 'brew install --cask' commands
cask_args appdir: "~/Applications", require_sha: true

# formula
brew "espanso"
brew "fd"               # required for some neovim plugins
brew "git"
brew "mas"
brew "neovim"
brew "node"             # required for some LSP servers in neovim
brew "pure"
brew "ripgrep"
brew "stow"
brew "swift-format"
brew "tmux"
brew "zsh"
brew "zsh-completions"

# fonts
cask "font-inconsolata-nerd-font"
