#!/bin/sh

set -e

# Installs launchd agents for appropriately.

agent="$HOME/Library/LaunchAgents"
uid="$(id -u "$(whoami)")"

test -d "$agent"

for file in "$DOTFILES"/macOS/LaunchAgents/*.plist; do
  filename="$(basename $file)"
  path="$agent/$filename"
  if ! test -e "$path"; then
    echo "Installing Agent: $filename"
    cp "$file" "$path"
    launchctl enable "user/$uid/$filename"
  fi
done
