#!/bin/bash

set -e

function installEspansoPackages() {
  echo "Installing packages..."
  espanso install mac-symbols
  espanso install all-emojis
  echo "Restarting espanso"
  espanso restart
}

installEspansoPackages
