#!/bin/sh

config="${HOME}/.config"
local_rc="${PWD}/config/.zshrc"
local_env="${PWD}/config/.zshenv"
local_funcs="${PWD}/config/zsh-functions"

_make_dirs() {
 mkdir "${config}"
 mkdir "${config}/zsh"
}

_make_links() {
  ln -sfv "${local_env}" "${HOME}"
  ln -sfv "${local_rc}" "${config}/zsh"
  ln -sfv "${local_funcs}" "${config}/zsh"
}

# -------------- main -------------------
_make_dirs
_make_links
