#!/usr/bin/env zsh

# Open's neovim.
#
# If the argument passed in is a directory or not supplied, then
# open neovim with telescope find files opened. Otherwise open the
# file that is supplied.
#

function n() {
  # if [ -z "$1" ]; then
  #   local gitdir=$(git rev-parse --show-toplevel 2> /dev/null)
  #
  #   [ -n "$gitdir" ] \
  #     && nvim -c ":Telescope git_files" \
  #     && return 0
  #
  #   [ -d "$1" ] \
  #     && nvim -c ":Telescope find_files" \
  #     && return 0
  # fi

  nvim "$1"
}

