#!/usr/bin/env zsh

# Open's neovim.
#
# If the argument passed in is a directory or not supplied, then
# open neovim with telescope find files opened. Otherwise open the
# file that is supplied.
#

function n() {
  [ -d "$1" ] || [ -z "$1" ] \
    && nvim -c ":Telescope find_files" \
    && return 0

  nvim "$1"
}

